### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by Simplifier** [postsharp-contrib/rider-readable-bitwise-operations#1]
I don't understand how to use it. It's not folded on file opening. Should I fold it manually every time?

**Comment by prochan2** [comment]
@Soothsilver ?

**Comment by Soothsilver** [comment]
It's tricky. It is suppose to auto-fold on file open, but Rider sometimes doesn't fold it and sometimes doesn't even allow you to fold it if you interact with the file. You can try closing and reopening the file or restarting Rider, but it was somewhat of a magic to me when I worked on this plugin.

I haven't used the plugin for a few years now, though, so I'm not sure if this functionality changed in any way with new versions of Rider, sorry.

**Comment by Simplifier** [comment]
Ok, thanks for the reply
